name: CI - Validate Actions

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  validate:
    name: Validate YAML & Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: JSON/YAML Validator
        uses: actions/setup-node@v6.1.0
        with:
            node-version: '24.12.0'

      - name: Install dependencies
        run: npm install -g yamllint

      - name: Lint YAML files
        run: yamllint .
