name: CI - Validate Actions

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  validate:
    name: Validate YAML & Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: JSON/YAML Validator
        uses: actions/setup-python@v6.1.0
        with:
            python-version: '3.14.2'

      - name: Install dependencies
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint .
