name: ğŸŒ CI - Distribute

on:
  workflow_call:

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Template Frontend Vite React
        uses: cyberskill-world/.github/actions/trigger-events@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: "cyberskill-world/template-fe-vite-react"
          EVENTS: |
            ğŸ“ˆ CI - Update

      - name: 2. Template Frontend NextJS
        uses: cyberskill-world/.github/actions/trigger-events@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: "cyberskill-world/template-fe-nextjs"
          EVENTS: |
            ğŸ“ˆ CI - Update

      - name: 3. Template Backend NodeJS
        uses: cyberskill-world/.github/actions/trigger-events@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: "cyberskill-world/template-be-nodejs"
          EVENTS: |
            ğŸ“ˆ CI - Update

      - name: 4. Template Backend NestJS
        uses: cyberskill-world/.github/actions/trigger-events@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: "cyberskill-world/template-be-nestjs"
          EVENTS: |
            ğŸ“ˆ CI - Update

      - name: 5. Template Mobile React Native
        uses: cyberskill-world/.github/actions/trigger-events@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: "cyberskill-world/template-mobile-react-native"
          EVENTS: |
            ğŸ“ˆ CI - Update

      - name: 6. Template Mobile Flutter
        uses: cyberskill-world/.github/actions/trigger-events@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: "cyberskill-world/template-mobile-flutter"
          EVENTS: |
            ğŸ“ˆ CI - Update

      - name: 7. Cyber Editor
        uses: cyberskill-world/.github/actions/trigger-events@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: "cyberskill-world/cyber-editor"
          EVENTS: |
            ğŸ“ˆ CI - Update

      # - name: 8. Cyber Sheet
      #   uses: cyberskill-world/.github/actions/trigger-events@main
      #   with:
      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
      #     REPO: "cyberskill-world/cyber-sheet"
      #     EVENTS: |
      #       ğŸ“ˆ CI - Update

      # - name: 9. Landing Page
      #   uses: cyberskill-world/.github/actions/trigger-events@main
      #   with:
      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
      #     REPO: "cyberskill-world/landing-page"
      #     EVENTS: |
      #       ğŸ“ˆ CI - Update

      - name: 10. CNLGaming Backend
        uses: cyberskill-world/.github/actions/trigger-events@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN_CNL }}
          REPO: "Cnlgaming-com/cnlgaming-be"
          EVENTS: |
            ğŸ“ˆ CI - Update

      - name: 11. CNLGaming Frontend
        uses: cyberskill-world/.github/actions/trigger-events@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN_CNL }}
          REPO: "Cnlgaming-com/cnlgaming-fe"
          EVENTS: |
            ğŸ“ˆ CI - Update
