name: ğŸŒ CS - Distribute
on:
  workflow_call:
jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      # Templates
      - name: Template Frontend Vite React
        uses: cyberskill-world/.github/actions/trigger-events@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: "cyberskill-world/template-fe-vite-react"
          EVENTS: |
            ğŸ“ˆ CI - Update

      - name: Template Frontend NextJS
        uses: cyberskill-world/.github/actions/trigger-events@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: "cyberskill-world/template-fe-nextjs"
          EVENTS: |
            ğŸ“ˆ CI - Update

      - name: Template Backend NodeJS
        uses: cyberskill-world/.github/actions/trigger-events@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: "cyberskill-world/template-be-nodejs"
          EVENTS: |
            ğŸ“ˆ CI - Update

      - name: Template Backend NestJS
        uses: cyberskill-world/.github/actions/trigger-events@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: "cyberskill-world/template-be-nestjs"
          EVENTS: |
            ğŸ“ˆ CI - Update

      - name: Template Mobile React Native
        uses: cyberskill-world/.github/actions/trigger-events@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: "cyberskill-world/template-mobile-react-native"
          EVENTS: |
            ğŸ“ˆ CI - Update

      - name: Template Mobile Flutter
        uses: cyberskill-world/.github/actions/trigger-events@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: "cyberskill-world/template-mobile-flutter"
          EVENTS: |
            ğŸ“ˆ CI - Update
      # Internal products
      - name: Cyber Editor
        uses: cyberskill-world/.github/actions/trigger-events@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: "cyberskill-world/cyber-editor"
          EVENTS: |
            ğŸ“ˆ CI - Update

      - name: Cyber Sheet
        uses: cyberskill-world/.github/actions/trigger-events@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: "cyberskill-world/cyber-sheet"
          EVENTS: |
            ğŸ“ˆ CI - Update

      - name: Landing Page
        uses: cyberskill-world/.github/actions/trigger-events@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: "cyberskill-world/landing-page"
          EVENTS: |
            ğŸ“ˆ CI - Update
      # CNLGaming
      - name: CNLGaming Backend
        uses: cyberskill-world/.github/actions/trigger-events@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN_CNL }}
          REPO: "Cnlgaming-com/cnlgaming-be"
          EVENTS: |
            ğŸ“ˆ CI - Update

      - name: CNLGaming Frontend
        uses: cyberskill-world/.github/actions/trigger-events@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN_CNL }}
          REPO: "Cnlgaming-com/cnlgaming-fe"
          EVENTS: |
            ğŸ“ˆ CI - Update
      # ODHQ
      - name: ODHQ Backend
        uses: cyberskill-world/.github/actions/trigger-events@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: "cyberskill-world/odhq-be"
          EVENTS: |
            ğŸ“ˆ CI - Update

      - name: ODHQ Admin
        uses: cyberskill-world/.github/actions/trigger-events@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: "cyberskill-world/odhq-admin"
          EVENTS: |
            ğŸ“ˆ CI - Update
